### ISSUE TITLE
Rewrite function "\wer"

### ISSUE THREAD

**Issue by ghost** [CptPie/telegram-shipit-bot#23]
Using an array of hardcoded names is not a good solution in regards to maintainability and scalability.

I'd rather use something like "msg.from.first_name", as its used in the function "/choose".

Currently, i don't have time to rewrite it by myself.

**Comment by CptPie** [comment]
i might try to put a jsonfile in place which saves all users to ensure the intention of the command (random name of group)

**Comment by ghost** [comment]
Isn't there any built-in feature that returns a list of all users within the group?

**Comment by CptPie** [comment]
nope there isnt afaik

**Comment by ghost** [comment]
https://core.telegram.org/bots/api#getchatmember

https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#TelegramBot+getChatMember

Maybe we can iterate over this function to get all the members In a list

**Comment by CptPie** [comment]
iterating would take ages imho because user ids are at least max. 9 digits long

**Comment by CptPie** [comment]
or as a simple alternative we could use a new /register command to save users locally into a file

**Comment by ghost** [comment]
Well, I didn't know that the user ids are that long. 

I was thinking that it goes from zero to "getGroupMemberCount" which is also a function

**Comment by CptPie** [comment]
wrote a prototype - its currently in testing

it uses a json file which stores the users in a array without duplicates
