### ISSUE TITLE
Choose doesn't work as expected

### ISSUE THREAD

**Issue by ghost** [CptPie/telegram-shipit-bot#30]
Input: /choose Kaffee, gruener Tee, schwarzer Tee
Output: @shipitbot has chosen Kaffee, gruener Tee for Manuel

Expected Output: Kaffee OR gruener Tee OR schwarzer Tee

**Comment by ghost** [comment]
I'm sorry, my fault.

Choose is only capable of choosing between 2 things.


You can close this issue anytime you want

**Comment by CptPie** [comment]
Closed as requested but might want to enhance the function for more options
