### ISSUE TITLE
wttr.in is down, so the bot throws lots of errors because of missing image source

### ISSUE THREAD

**Issue by CptPie** [CptPie/telegram-shipit-bot#46]
We should look into proper exception handling for all functions, because at the moment the console spam is real.
Also i consider to fork wttr.in's repo to ensure that the image source is available.

**Comment by ghost** [comment]
NOOOOOOOIIIIIIIIIIIINNNNNNNNNNNNNNNNNNNN

**Comment by CptPie** [comment]
rip wttr.in

**Comment by Kerru** [comment]
<3

**Comment by Kerru** [comment]
Instead of wttr.in use the yahoo weather api

**Comment by ghost** [comment]
works again
