### ISSUE TITLE
weather warning

### ISSUE THREAD

**Issue by ghost** [CptPie/telegram-shipit-bot#49]
I think that pushing information about a storm/bad weather in general would be a great feature. 

The information can be acquired from e.g. following site
http://www.unwetterzentrale.de/uwz/getwarning_de.php?id=UWZDE96050

**Comment by CptPie** [comment]
currently working on it.
using data from http://dwd.de/DWD/warnungen/warnapp/json/warnings.json
todos: 
-clean up json
-check if ids are permanently tied to a city or not
-do much json magic
-do even more regex magic

then it should be fine! its possible

**Comment by CptPie** [comment]
@CptPie github bot test
