### ISSUE TITLE
rework bot commands to work in the middle of a message

### ISSUE THREAD

**Issue by CptPie** [CptPie/telegram-shipit-bot#56]
![image](https://user-images.githubusercontent.com/23438606/30910229-2c17d2c4-a384-11e7-9f46-c25542a8eb12.png)

**Comment by ghost** [comment]
fixed with https://github.com/CptPie/telegram-shipit-bot/pull/59

**Comment by ghost** [comment]
Does not work in groups

**Comment by CptPie** [comment]
should be working now, if anyone has problems you need to disable privacy in your botfather menu
